
typedef union  {
	int   inv;
	char *str;
	float flo;
	} YYSTYPE;
extern YYSTYPE yylval;
# define LABEL 257
# define CONST 258
# define EPSILON 259
# define PRECISION 260
# define APPROXYMATION 261
# define NO 262
# define HIPER 263
# define NORMAL 264
# define POLY 265
# define LOGN 266
# define LOG2 267
# define LOG10 268
# define STANDART 269
# define DONE 270
# define ILLEGAL 271
